### ISSUE TITLE
Supported audio formats ?

### ISSUE THREAD

**Issue by bobir01** [bean-du/SpeakSense#2]
I am wondering how many different audio format does it support?
if only .wav, or should we handle audio convertion ourselves?

**Comment by bobir01** [comment]
@bean-du

**Comment by bean-du** [comment]
If you use HTTP to add a transcribe task. It support all ffmpeg support audio format. But gRPC only support WAV. You must handle it in your gRPC client. moreover,  If you use gRPC you also must handle audio sample to 16k. There is an example: https://github.com/bean-du/SpeakSense/blob/main/examples/asr_client.rs @bobir01
